services:
  kaow-api:
    build:
      context: ./KAOW
      dockerfile: Dockerfile
    container_name: kaow-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=tcp:sqlserver-kaow.database.windows.net,1433;Initial Catalog=kaow-db-dev;Persist Security Info=False;User ID=admsql;Password=devops@Fiap2tds;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    restart: on-failure
    networks:
      - kaow-network

networks:
  kaow-network:
    name: kaow-network
    driver: bridge
